import os
import sys
import subprocess
import shutil
import importlib.util
import inspect
import json

def execute(task=None, **kwargs):
    """
    TITAN EXPANDER: Autonomous Skill Acquisition (ASA)
    Downloads a GitHub repository and integrates it as a first-class JACK skill.
    """
    if not task:
        return "ASA Error: Please provide a GitHub repository URL or 'username/repo'."

    repo_url = task
    print(f"ASA Engine: Initiating targeted absorption of {repo_url}...")

    try:
        # 1. Install via GitHubInstaller
        from setup_tools.github_installer import GitHubInstaller
        installer = GitHubInstaller()
        
        # This clones the repo into skills/
        install_res = installer.install_skill(repo_url)
        if "FAILED" in install_res.upper():
            return install_res

        repo_name = repo_url.split("/")[-1].replace(".git", "")
        skill_path = os.path.join("skills", repo_name)

        # 2. Logic: Analyze and Wrap
        # We need to find the "main" entry point to create a successful action.py
        wrap_res = _autonomously_wrap_repo(skill_path, repo_name)
        
        # 3. Refresh Skill Manager
        try:
            from skill_manager import skill_manager
            skill_manager.load_skills()
        except: pass

        return f"ASA SUCCESS: {repo_name} has been absorbed into the TITAN collective.\n{wrap_res}"

    except Exception as e:
        return f"ASA Failure: {str(e)}"

def _autonomously_wrap_repo(skill_path, repo_name):
    """Scan the cloned repo and generate a valid action.py wrapper."""
    print(f"ASA Engine: Analyzing {repo_name} architecture...")
    
    # 1. Look for obvious entry points
    priority_files = ["main.py", "app.py", "run.py", f"{repo_name}.py"]
    entry_point = None
    
    for f in priority_files:
        p = os.path.join(skill_path, f)
        if os.path.exists(p):
            entry_point = f
            break
            
    if not entry_point:
        # Scan for any python file that isn't setup.py
        for f in os.listdir(skill_path):
            if f.endswith(".py") and f != "setup.py" and f != "action.py":
                entry_point = f
                break

    if not entry_point:
        return "Logic Warning: No clear Python entry point found. Integrated as a library only."

    # 2. Generate the wrapper
    # We'll create an action.py that imports the entry point and tries to find a main runner
    wrapper_code = f'''import os
import sys
import importlib.util

# Add skill directory to path for imports
SKILL_DIR = os.path.dirname(os.path.abspath(__file__))
if SKILL_DIR not in sys.path:
    sys.path.append(SKILL_DIR)

def execute(task=None, **kwargs):
    """Wrapper for {repo_name} generated by TITAN ASA."""
    try:
        # Import the detected entry point: {entry_point}
        module_name = "{entry_point.replace('.py', '')}"
        spec = importlib.util.spec_from_file_location(module_name, os.path.join(SKILL_DIR, "{entry_point}"))
        module = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(module)
        
        # Strategy: Look for common execution patterns
        if hasattr(module, "main"):
            if task: return module.main(task)
            return module.main()
        elif hasattr(module, "run"):
            if task: return module.run(task)
            return module.run()
        elif hasattr(module, "execute"):
            return module.execute(task)
        else:
            return f"Skill '{repo_name}' absorbed, but no standard 'main' or 'run' function found in {entry_point}."
            
    except Exception as e:
        return f"Skill Error ({repo_name}): {{e}}"
'''

    with open(os.path.join(skill_path, "action.py"), "w") as f:
        f.write(wrapper_code)

    return f"Logic: Created 'action.py' wrapper for {entry_point}."
